package leomaia.musicmananger.GUI;

import javax.swing.AbstractListModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import leomaia.musicmananger.ColecaoMusicasPrincipal;
import leomaia.musicmananger.ColecaoParticular;
import leomaia.musicmananger.Musica;
import leomaia.musicmananger.PersistenciaUsuario;
import leomaia.musicmananger.Usuario;

/**
 *
 * @author leoma
 */
public class App extends javax.swing.JFrame {
    private Usuario user;
    private Usuario usuarioSelecionado;
    private ColecaoMusicasPrincipal colecao;
    private ColecaoParticular colecaoParticular;
    private boolean ADM;
    private Musica musicaBSelecionada;
    private Musica musicaPSelecionada;
    private DefaultListModel<Musica> LMBiblioteca;
    private DefaultListModel<Musica> LMPlaylist;
    private DefaultListModel<Usuario> LMUsuarios;
    /**
     * Creates new form GUIApp
     */
    
    public App() {
        initComponents();
        colecao = new ColecaoMusicasPrincipal();
        colecao.carregarColecao();
        //colecao.imprimirColecao();
        TelaLogin TL = new TelaLogin(this, true);
        TL.setVisible(true);
        user = TL.getUser();
        colecaoParticular = new ColecaoParticular();
        colecaoParticular.carregarParticular(user.getLogin(), colecao);
        //colecaoParticular.imprimirColecaoParticular();
        LMUsuarios = PersistenciaUsuario.usuarioToListModel();
        LMBiblioteca = ColecaoMusicasPrincipal.colecaoToListmodel(colecao.getMusicas());
        LMPlaylist = ColecaoMusicasPrincipal.colecaoToListmodel(colecaoParticular.getMusicas());
        jListBiblioteca.setModel(LMBiblioteca);
        jListMinhaPlaylist.setModel(LMPlaylist);
        ADM = user.isAdmin();
        apagarUsuario1.setVisible(ADM);
        novoAMD.setVisible(ADM);
        addNovaMusica.setVisible(ADM);
        removerMusicaBiblioteca.setVisible(ADM);
        editarMusicaBiblioteca.setVisible(ADM);
        jListUsuario.setVisible(ADM);
        jListUsuario.setModel(LMUsuarios);
    } 
    
    private void buscaFiltroB(String buscado){
        DefaultListModel<Musica> filtroB = new DefaultListModel<>();
        for (int i = 0; i < LMBiblioteca.size(); i++) {
            Musica musica = LMBiblioteca.getElementAt(i);
            String elem = musica.toString().toLowerCase();
            if(elem.contains(buscado.toLowerCase())){
                filtroB.addElement(musica);
            }
        }
        jListBiblioteca.setModel(filtroB);
    }
    
    private void buscaFiltroP(String buscado){
        DefaultListModel<Musica> filtroP = new DefaultListModel<>();
        for (int i = 0; i < LMPlaylist.size(); i++) {
            Musica musica = LMPlaylist.getElementAt(i);
            String elem = musica.toString().toLowerCase();
            if(elem.contains(buscado.toLowerCase())){
                filtroP.addElement(musica);
            }
        }
        jListMinhaPlaylist.setModel(filtroP);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idDetalhesB = new javax.swing.JLabel();
        tipoDetalhesB = new javax.swing.JLabel();
        tituloDetalhesB = new javax.swing.JLabel();
        autoresDetalhesB = new javax.swing.JLabel();
        generoDetalhesB = new javax.swing.JLabel();
        duracaoDetalhesB = new javax.swing.JLabel();
        anoDetalhesB = new javax.swing.JLabel();
        Jbemvindo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListBiblioteca = new javax.swing.JList<>();
        exibirLetraBiblioteca = new javax.swing.JButton();
        addMusicaPlaylist = new javax.swing.JButton();
        removerMusicaBiblioteca = new javax.swing.JButton();
        addNovaMusica = new javax.swing.JButton();
        editarMusicaBiblioteca = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        buscaTxtB = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        idDetalhesP = new javax.swing.JLabel();
        tipoDetalhesP = new javax.swing.JLabel();
        tituloDetalhesP = new javax.swing.JLabel();
        autoresDetalhesP = new javax.swing.JLabel();
        generoDetalhesP = new javax.swing.JLabel();
        duracaoDetalhesP = new javax.swing.JLabel();
        anoDetalhesP = new javax.swing.JLabel();
        Jbemvindo1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListMinhaPlaylist = new javax.swing.JList<>();
        exibirLetraPlaylist = new javax.swing.JButton();
        removerMusicaPlaylist = new javax.swing.JButton();
        buscaTxtP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        apagarMeuUsuario = new javax.swing.JButton();
        sairBT = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListUsuario = new javax.swing.JList<>();
        apagarUsuario1 = new javax.swing.JButton();
        novoAMD = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Músicas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(29, 185, 84));

        jTabbedPane5.setBackground(new java.awt.Color(33, 33, 33));
        jTabbedPane5.setForeground(new java.awt.Color(0, 204, 51));
        jTabbedPane5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(33, 33, 33));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Biblioteca");

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Título:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Autores:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gênero:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Duração:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ano:");

        idDetalhesB.setForeground(new java.awt.Color(255, 255, 255));

        tipoDetalhesB.setForeground(new java.awt.Color(255, 255, 255));

        tituloDetalhesB.setForeground(new java.awt.Color(255, 255, 255));

        autoresDetalhesB.setForeground(new java.awt.Color(255, 255, 255));

        generoDetalhesB.setForeground(new java.awt.Color(255, 255, 255));

        duracaoDetalhesB.setForeground(new java.awt.Color(255, 255, 255));

        anoDetalhesB.setForeground(new java.awt.Color(255, 255, 255));

        Jbemvindo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Jbemvindo.setForeground(new java.awt.Color(255, 255, 255));
        Jbemvindo.setText("Detalhes ");
        Jbemvindo.setToolTipText("");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(duracaoDetalhesB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(generoDetalhesB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(autoresDetalhesB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tituloDetalhesB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tipoDetalhesB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idDetalhesB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(anoDetalhesB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(Jbemvindo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(Jbemvindo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(idDetalhesB)
                        .addGap(18, 18, 18)
                        .addComponent(tipoDetalhesB)
                        .addGap(18, 18, 18)
                        .addComponent(tituloDetalhesB)
                        .addGap(18, 18, 18)
                        .addComponent(autoresDetalhesB)
                        .addGap(18, 18, 18)
                        .addComponent(generoDetalhesB)
                        .addGap(18, 18, 18)
                        .addComponent(duracaoDetalhesB)
                        .addGap(18, 18, 18)
                        .addComponent(anoDetalhesB))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jListBiblioteca.setBackground(new java.awt.Color(51, 51, 51));
        jListBiblioteca.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jListBiblioteca.setForeground(new java.awt.Color(255, 255, 255));
        jListBiblioteca.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListBiblioteca.setSelectionBackground(new java.awt.Color(29, 185, 84));
        jListBiblioteca.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListBibliotecaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListBiblioteca);

        exibirLetraBiblioteca.setBackground(new java.awt.Color(29, 185, 84));
        exibirLetraBiblioteca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exibirLetraBiblioteca.setForeground(new java.awt.Color(255, 255, 255));
        exibirLetraBiblioteca.setText("EXIBIR LETRA");
        exibirLetraBiblioteca.setBorder(null);
        exibirLetraBiblioteca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exibirLetraBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirLetraBibliotecaActionPerformed(evt);
            }
        });

        addMusicaPlaylist.setBackground(new java.awt.Color(29, 185, 84));
        addMusicaPlaylist.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addMusicaPlaylist.setForeground(new java.awt.Color(255, 255, 255));
        addMusicaPlaylist.setText("ADICIONAR A MINHA PLAYLIST");
        addMusicaPlaylist.setBorder(null);
        addMusicaPlaylist.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addMusicaPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMusicaPlaylistActionPerformed(evt);
            }
        });

        removerMusicaBiblioteca.setBackground(new java.awt.Color(29, 185, 84));
        removerMusicaBiblioteca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        removerMusicaBiblioteca.setForeground(new java.awt.Color(255, 255, 255));
        removerMusicaBiblioteca.setText("REMOVER");
        removerMusicaBiblioteca.setBorder(null);
        removerMusicaBiblioteca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removerMusicaBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerMusicaBibliotecaActionPerformed(evt);
            }
        });

        addNovaMusica.setBackground(new java.awt.Color(29, 185, 84));
        addNovaMusica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addNovaMusica.setForeground(new java.awt.Color(255, 255, 255));
        addNovaMusica.setText("NOVA MÚSICA");
        addNovaMusica.setBorder(null);
        addNovaMusica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addNovaMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNovaMusicaActionPerformed(evt);
            }
        });

        editarMusicaBiblioteca.setBackground(new java.awt.Color(29, 185, 84));
        editarMusicaBiblioteca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editarMusicaBiblioteca.setForeground(new java.awt.Color(255, 255, 255));
        editarMusicaBiblioteca.setText("EDITAR");
        editarMusicaBiblioteca.setBorder(null);
        editarMusicaBiblioteca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editarMusicaBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarMusicaBibliotecaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Buscar");

        buscaTxtB.setBackground(new java.awt.Color(51, 51, 51));
        buscaTxtB.setForeground(new java.awt.Color(255, 255, 255));
        buscaTxtB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 3));
        buscaTxtB.setCaretColor(new java.awt.Color(255, 255, 255));
        buscaTxtB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscaTxtBKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscaTxtB)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exibirLetraBiblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addMusicaPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(addNovaMusica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(removerMusicaBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarMusicaBiblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(exibirLetraBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addMusicaPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(removerMusicaBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editarMusicaBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addNovaMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(buscaTxtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Biblioteca", jPanel1);

        jPanel7.setBackground(new java.awt.Color(33, 33, 33));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Minha Playlist");

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("ID:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Tipo:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Título:");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Autores:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Gênero:");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Duração:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Ano:");

        idDetalhesP.setForeground(new java.awt.Color(255, 255, 255));

        tipoDetalhesP.setForeground(new java.awt.Color(255, 255, 255));

        tituloDetalhesP.setForeground(new java.awt.Color(255, 255, 255));

        autoresDetalhesP.setForeground(new java.awt.Color(255, 255, 255));

        generoDetalhesP.setForeground(new java.awt.Color(255, 255, 255));

        duracaoDetalhesP.setForeground(new java.awt.Color(255, 255, 255));

        anoDetalhesP.setForeground(new java.awt.Color(255, 255, 255));

        Jbemvindo1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Jbemvindo1.setForeground(new java.awt.Color(255, 255, 255));
        Jbemvindo1.setText("Detalhes");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(duracaoDetalhesP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(generoDetalhesP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(autoresDetalhesP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tituloDetalhesP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tipoDetalhesP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idDetalhesP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(anoDetalhesP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(Jbemvindo1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 127, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(Jbemvindo1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(idDetalhesP)
                        .addGap(18, 18, 18)
                        .addComponent(tipoDetalhesP)
                        .addGap(18, 18, 18)
                        .addComponent(tituloDetalhesP)
                        .addGap(18, 18, 18)
                        .addComponent(autoresDetalhesP)
                        .addGap(18, 18, 18)
                        .addComponent(generoDetalhesP)
                        .addGap(18, 18, 18)
                        .addComponent(duracaoDetalhesP)
                        .addGap(18, 18, 18)
                        .addComponent(anoDetalhesP))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jListMinhaPlaylist.setBackground(new java.awt.Color(51, 51, 51));
        jListMinhaPlaylist.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jListMinhaPlaylist.setForeground(new java.awt.Color(255, 255, 255));
        jListMinhaPlaylist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListMinhaPlaylist.setSelectionBackground(new java.awt.Color(29, 185, 84));
        jListMinhaPlaylist.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListMinhaPlaylistValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListMinhaPlaylist);

        exibirLetraPlaylist.setBackground(new java.awt.Color(29, 185, 84));
        exibirLetraPlaylist.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exibirLetraPlaylist.setForeground(new java.awt.Color(255, 255, 255));
        exibirLetraPlaylist.setText("EXIBIR LETRA");
        exibirLetraPlaylist.setBorder(null);
        exibirLetraPlaylist.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exibirLetraPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirLetraPlaylistActionPerformed(evt);
            }
        });

        removerMusicaPlaylist.setBackground(new java.awt.Color(29, 185, 84));
        removerMusicaPlaylist.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        removerMusicaPlaylist.setForeground(new java.awt.Color(255, 255, 255));
        removerMusicaPlaylist.setText("REMOVER DA PLAYLIST");
        removerMusicaPlaylist.setBorder(null);
        removerMusicaPlaylist.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removerMusicaPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerMusicaPlaylistActionPerformed(evt);
            }
        });

        buscaTxtP.setBackground(new java.awt.Color(51, 51, 51));
        buscaTxtP.setForeground(new java.awt.Color(255, 255, 255));
        buscaTxtP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 3));
        buscaTxtP.setCaretColor(new java.awt.Color(255, 255, 255));
        buscaTxtP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchB(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Buscar");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscaTxtP))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removerMusicaPlaylist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exibirLetraPlaylist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel16)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(exibirLetraPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removerMusicaPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(buscaTxtP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Minha Playlist", jPanel7);

        jPanel3.setBackground(new java.awt.Color(33, 33, 33));

        apagarMeuUsuario.setBackground(new java.awt.Color(29, 185, 84));
        apagarMeuUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        apagarMeuUsuario.setForeground(new java.awt.Color(255, 255, 255));
        apagarMeuUsuario.setText("APAGAR MINHA CONTA");
        apagarMeuUsuario.setBorder(null);
        apagarMeuUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        apagarMeuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarMeuUsuarioActionPerformed(evt);
            }
        });

        sairBT.setBackground(new java.awt.Color(29, 185, 84));
        sairBT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sairBT.setForeground(new java.awt.Color(255, 255, 255));
        sairBT.setText("FAZER LOGOUT");
        sairBT.setBorder(null);
        sairBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sairBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairBTActionPerformed(evt);
            }
        });

        jListUsuario.setBackground(new java.awt.Color(51, 51, 51));
        jListUsuario.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jListUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jListUsuario.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListUsuario.setSelectionBackground(new java.awt.Color(29, 185, 84));
        jListUsuario.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListUsuarioValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jListUsuario);

        apagarUsuario1.setBackground(new java.awt.Color(29, 185, 84));
        apagarUsuario1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        apagarUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        apagarUsuario1.setText("APAGAR USUÁRIO");
        apagarUsuario1.setBorder(null);
        apagarUsuario1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        apagarUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarUsuario1ActionPerformed(evt);
            }
        });

        novoAMD.setBackground(new java.awt.Color(29, 185, 84));
        novoAMD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        novoAMD.setForeground(new java.awt.Color(255, 255, 255));
        novoAMD.setText("CADASTRAR NOVO AMD");
        novoAMD.setBorder(null);
        novoAMD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        novoAMD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoAMDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apagarMeuUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(sairBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(apagarUsuario1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(novoAMD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(206, 206, 206))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(apagarMeuUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(apagarUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sairBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(novoAMD, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Usuario", jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane5)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jListMinhaPlaylistValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListMinhaPlaylistValueChanged
        this.musicaPSelecionada = jListMinhaPlaylist.getSelectedValue();
        //System.out.println(musicaBSelecionada.getTitulo());
        if(musicaPSelecionada != null){
            idDetalhesP.setText(String.valueOf(musicaPSelecionada.getId()));
            tipoDetalhesP.setText(musicaPSelecionada.tipoMusica());
            tituloDetalhesP.setText(musicaPSelecionada.getTitulo());
            autoresDetalhesP.setText(musicaPSelecionada.getAutores());
            duracaoDetalhesP.setText(musicaPSelecionada.getDuracao());
            generoDetalhesP.setText(musicaPSelecionada.getGeneroMusical());
            anoDetalhesP.setText(musicaPSelecionada.getDataStr());
        }
    }//GEN-LAST:event_jListMinhaPlaylistValueChanged

    private void jListBibliotecaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListBibliotecaValueChanged
        this.musicaBSelecionada = jListBiblioteca.getSelectedValue();
        if(musicaBSelecionada != null){
        //System.out.println(musicaBSelecionada.getTitulo());
            idDetalhesB.setText(String.valueOf(musicaBSelecionada.getId()));
            tipoDetalhesB.setText(musicaBSelecionada.tipoMusica());
            tituloDetalhesB.setText(musicaBSelecionada.getTitulo());
            autoresDetalhesB.setText(musicaBSelecionada.getAutores());
            duracaoDetalhesB.setText(musicaBSelecionada.getDuracao());
            generoDetalhesB.setText(musicaBSelecionada.getGeneroMusical());
            anoDetalhesB.setText(musicaBSelecionada.getDataStr());
        }
    }//GEN-LAST:event_jListBibliotecaValueChanged

    private void exibirLetraBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirLetraBibliotecaActionPerformed
        MostrarLetra L = new MostrarLetra(this, true, musicaBSelecionada.letraCancao());
        L.setVisible(true);
    }//GEN-LAST:event_exibirLetraBibliotecaActionPerformed

    private void exibirLetraPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirLetraPlaylistActionPerformed
        MostrarLetra L = new MostrarLetra(this, true, musicaPSelecionada.letraCancao());
        L.setVisible(true);
    }//GEN-LAST:event_exibirLetraPlaylistActionPerformed

    private void searchB(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchB
        buscaFiltroP(buscaTxtP.getText());
    }//GEN-LAST:event_searchB

    private void buscaTxtBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscaTxtBKeyReleased
        buscaFiltroB(buscaTxtB.getText());
    }//GEN-LAST:event_buscaTxtBKeyReleased

    private void addMusicaPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMusicaPlaylistActionPerformed
        colecaoParticular.adicionarMusica(musicaBSelecionada, user.getLogin());
        LMPlaylist = ColecaoMusicasPrincipal.colecaoToListmodel(colecaoParticular.getMusicas());
        jListMinhaPlaylist.setModel(LMPlaylist);
        JOptionPane.showMessageDialog(null, musicaBSelecionada.toString()+"\nAdicionada a Minha Playlist");
    }//GEN-LAST:event_addMusicaPlaylistActionPerformed

    private void removerMusicaPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerMusicaPlaylistActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja remover um item?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            colecaoParticular.removerMusica(musicaPSelecionada, user.getLogin());
            LMPlaylist = ColecaoMusicasPrincipal.colecaoToListmodel(colecaoParticular.getMusicas());
            jListMinhaPlaylist.setModel(LMPlaylist); 
        }
    }//GEN-LAST:event_removerMusicaPlaylistActionPerformed

    private void addNovaMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNovaMusicaActionPerformed
        TelaAddMusica T = new TelaAddMusica(this, true, colecao);
        T.setVisible(true);
        colecao.carregarColecao();
        LMBiblioteca = ColecaoMusicasPrincipal.colecaoToListmodel(colecao.getMusicas());
        jListBiblioteca.setModel(LMBiblioteca);
    }//GEN-LAST:event_addNovaMusicaActionPerformed

    private void removerMusicaBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerMusicaBibliotecaActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja remover um item?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
           colecao.removerMusica(musicaBSelecionada, colecao.getMusicas());
            musicaBSelecionada = null;
            colecao.carregarColecao();
            LMBiblioteca = ColecaoMusicasPrincipal.colecaoToListmodel(colecao.getMusicas());
            jListBiblioteca.setModel(LMBiblioteca); 
        }
        
        
    }//GEN-LAST:event_removerMusicaBibliotecaActionPerformed

    private void editarMusicaBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarMusicaBibliotecaActionPerformed
        TelaEditarMusica T = new TelaEditarMusica(this, true, colecao, musicaBSelecionada);
        T.setVisible(true);
        colecao.carregarColecao();
        LMBiblioteca = ColecaoMusicasPrincipal.colecaoToListmodel(colecao.getMusicas());
        jListBiblioteca.setModel(LMBiblioteca);
    }//GEN-LAST:event_editarMusicaBibliotecaActionPerformed

    private void apagarMeuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarMeuUsuarioActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja apagar usuario?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            Usuario.removerUsuario(user.getLogin());
            new App().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_apagarMeuUsuarioActionPerformed

    private void sairBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairBTActionPerformed
        new App().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sairBTActionPerformed

    private void jListUsuarioValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListUsuarioValueChanged
        
        
    }//GEN-LAST:event_jListUsuarioValueChanged

    private void apagarUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarUsuario1ActionPerformed
        this.usuarioSelecionado = jListUsuario.getSelectedValue();
        if(!(user.getLogin().equals(usuarioSelecionado.getLogin()))){
            int resposta = JOptionPane.showConfirmDialog(null, "Deseja apagar usuario?", "Confirmação", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                Usuario.removerUsuario(usuarioSelecionado.getLogin());
                LMUsuarios = PersistenciaUsuario.usuarioToListModel();
                jListUsuario.setModel(LMUsuarios);
            }
        }
    }//GEN-LAST:event_apagarUsuario1ActionPerformed

    private void novoAMDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoAMDActionPerformed
        TelaCadastroADM TL = new TelaCadastroADM(this, true);
        TL.setVisible(true);
    }//GEN-LAST:event_novoAMDActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new App().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jbemvindo;
    private javax.swing.JLabel Jbemvindo1;
    private javax.swing.JButton addMusicaPlaylist;
    private javax.swing.JButton addNovaMusica;
    private javax.swing.JLabel anoDetalhesB;
    private javax.swing.JLabel anoDetalhesP;
    private javax.swing.JButton apagarMeuUsuario;
    private javax.swing.JButton apagarUsuario1;
    private javax.swing.JLabel autoresDetalhesB;
    private javax.swing.JLabel autoresDetalhesP;
    private javax.swing.JTextField buscaTxtB;
    private javax.swing.JTextField buscaTxtP;
    private javax.swing.JLabel duracaoDetalhesB;
    private javax.swing.JLabel duracaoDetalhesP;
    private javax.swing.JButton editarMusicaBiblioteca;
    private javax.swing.JButton exibirLetraBiblioteca;
    private javax.swing.JButton exibirLetraPlaylist;
    private javax.swing.JLabel generoDetalhesB;
    private javax.swing.JLabel generoDetalhesP;
    private javax.swing.JLabel idDetalhesB;
    private javax.swing.JLabel idDetalhesP;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<Musica> jListBiblioteca;
    private javax.swing.JList<Musica> jListMinhaPlaylist;
    private javax.swing.JList<Usuario> jListUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JButton novoAMD;
    private javax.swing.JButton removerMusicaBiblioteca;
    private javax.swing.JButton removerMusicaPlaylist;
    private javax.swing.JButton sairBT;
    private javax.swing.JLabel tipoDetalhesB;
    private javax.swing.JLabel tipoDetalhesP;
    private javax.swing.JLabel tituloDetalhesB;
    private javax.swing.JLabel tituloDetalhesP;
    // End of variables declaration//GEN-END:variables
}
